# DATA
datalink: "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
dataname: heart_dataset
datarawdirectory: data/raw/
datainterimdirectory: data/interim/
dataprocesseddirectory: data/processed/

# MODELS
modeltype: NeuralNetwork
modelpath: models/

# RESULTS
resultsrawpath: results/results_raw_
resultsevaluatedpath: results/results_evaluated_

# VISUALIZATION
figuredirectory: reports/figures/
