# DATA 
datalink: "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
dataname: iris
datarawdirectory: data/raw/
datainterimdirectory: data/interim/
dataprocesseddirectory: data/processed/

# MODELS
modelpath: models/model.pkl

# RESULTS
resultsrawpath: results/results_raw.pkl
resultsevaluatedpath: results/results_evaluated.pkl

# VISUALIZATION
figuredirectory: reports/figures/
